#!/bin/bash

set -euo pipefail

exec 3>&1
exec 1>&2
payload="$(cat <&0)"

domain=$(jq -r .source.domain <<< "$payload")
echo "machine $domain" > ~/.netrc
if [ "$(jq -r '.source | has("username")' <<< "$payload")" = 'true' ]; then
    username=$(jq -r .source.username <<< "$payload")
    echo "  login $username" >> ~/.netrc
fi
if [ "$(jq -r '.source | has("password")' <<< "$payload")" = 'true' ]; then
    password=$(jq -r .source.password <<< "$payload")
    echo "  password $password" >> ~/.netrc
fi
if [ "$(jq -r '.source | has("ssl")' <<< "$payload")" = 'true' ]; then
    ssl=$(jq -r .source.ssl <<< "$payload")
    if [ "$ssl" = "false" ]; then
        url="http://$domain"
    else
        url="https://$domain"
    fi
else
    url="https://$domain"
fi
if [ "$(jq -r '.source | has("port")' <<< "$payload")" = 'true' ]; then
    port=$(jq -r .source.port <<< "$payload")
    url+=":$port"
fi
if [ "$(jq -r '.source | has("path")' <<< "$payload")" = 'true' ]; then
    path=$(jq -r .source.path <<< "$payload")
    url+="/$path/"
else
    url+="/"
fi

trim() {
    local var="$*"
    # remove leading whitespace characters
    var="${var#"${var%%[![:space:]]*}"}"
    # remove trailing whitespace characters
    var="${var%"${var##*[![:space:]]}"}"
    printf '%s' "$var"
}

if ! echo "echo ping" | cadaver "$url" | grep "Connection to \`$domain' closed." >/dev/null 2>&1; then
    echo "Connection error."
    exit 1
fi

lines=()
while read -r line; do
    if [ -n "$line" ]; then
        lines+=("$(trim "$line")")
    fi
done < <(echo ls | cadaver "$url" | head -n -2)

IFS=$'\n'
echo "${lines[*]:2}" | sort
sha256=$(echo "${lines[*]:2}" | sort | sha256sum | awk '{print $1}')

json='[{"digest":"'"sha256:$sha256"'","url":"'"$url"'"}]'

jq -n "$json" >&3
