#!/bin/bash

set -euo pipefail

exec 3>&1
exec 1>&2
jq -M -S . < /dev/stdin > /tmp/input.json

domain=$(jq -r .source.domain < /tmp/input.json)
echo "machine $domain" > ~/.netrc
if [ "$(jq -r '.source | has("username")' < /tmp/input.json)" = 'true' ]; then
    username=$(jq -r .source.username < /tmp/input.json)
    echo "  login $username" >> ~/.netrc
fi
if [ "$(jq -r '.source | has("password")' < /tmp/input.json)" = 'true' ]; then
    password=$(jq -r .source.password < /tmp/input.json)
    echo "  password $password" >> ~/.netrc
fi
if [ "$(jq -r '.source | has("ssl")' < /tmp/input.json)" = 'true' ]; then
    ssl=$(jq -r .source.ssl < /tmp/input.json)
    if [ "$ssl" = "false" ]; then
        url="http://$domain"
    else
        url="https://$domain"
    fi
else
    url="https://$domain"
fi
if [ "$(jq -r '.source | has("port")' < /tmp/input.json)" = 'true' ]; then
    port=$(jq -r .source.port < /tmp/input.json)
    url+=":$port"
fi
if [ "$(jq -r '.source | has("path")' < /tmp/input.json)" = 'true' ]; then
    path=$(jq -r .source.path < /tmp/input.json)
    url+="/$path/"
else
    url+="/"
fi

lines=()
while read -r line; do
    if [ -n "$line" ]; then
        lines+=("$line")
    fi
done < <(echo ls | cadaver "$url" | head -n -2)

sha256=$(echo "${lines[@]:2}" | sha256sum | awk '{print $1}')

json='[{"sha256":"'"$sha256"'","url":"'"$url"'"}]'

jq -n "$json" >&3
